version: "3"
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.2.0-actinium
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
  app:
    build: ./scraping
    volumes:
      - ./scraping:/scraping
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
