version: "3"
services:
  selenium:
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
      - 4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
  app:
    build: ./scraping
    volumes:
      - ./scraping:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true